-- LifeFlow Pro billing state
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'lemonsqueezy',
  provider_subscription_id text,
  provider_customer_id text,
  provider_order_id text,
  product_id text,
  variant_id text,
  status text not null default 'inactive',
  renews_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, provider_subscription_id)
);

create index if not exists subscriptions_user_id_idx on public.subscriptions(user_id);
create index if not exists subscriptions_status_idx on public.subscriptions(status);

alter table public.subscriptions enable row level security;

drop policy if exists "Users can view own subscriptions" on public.subscriptions;
create policy "Users can view own subscriptions"
on public.subscriptions for select
using (auth.uid() = user_id);

-- Only server-side webhook code should insert/update subscription rows.
-- No client insert/update/delete policies are created intentionally.
